language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
# command to install dependencies
install:
  - MINICONDA=Miniconda3-latest-Linux-x86_64.sh
  - MINICONDA_MD5=$(curl -s http://repo.continuum.io/miniconda/ | grep -A3 $MINICONDA | sed -n '4p' | sed -n 's/ *<td>\(.*\)<\/td> */\1/p')
  - wget http://repo.continuum.io/miniconda/$MINICONDA
  - if [[ $MINICONDA_MD5 != $(md5sum $MINICONDA | cut -d ' ' -f 1) ]]; then  echo "Miniconda MD5 mismatch"; exit 1; fi
  - bash $MINICONDA -b
  - export PATH=$HOME/miniconda3/bin:$PATH

  # install requirements file in python
  - conda create --yes -n test python=$python `cat requirements.txt | xargs`
  - source activate test

  # install pip
  - conda install --yes pip

  # install python2.6 backports
  - '[ "$python" = "2.6" ]
      && pip install importlib argparse
      || echo ""'

  # install extra dependency for style checking
  - conda install --yes flake8

# command to run tests
script: 
script:
  - nosetests -v
  - flake8 `find . -name '*.py'  ! -name build ! -path './build/*' !
            -path './docs*' | xargs`