language: python
python:
  - "3.5"

branches:
  only:
    - master
install:
  - source devtools/ci/install.sh

script:
  - nosetests -v
  #- flake8 `find . -name '*.py'  ! -name build ! -path './build/*' !
   #         -path './docs*' | xargs`
